/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 90s_stylized_office.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desktop(props) {
  const { nodes, materials } = useGLTF('./models/90s_stylized_office.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[16.125, 2.994, -78.824]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Chair_mChair_0.geometry} material={materials['m.Chair']} />
          <mesh geometry={nodes.ChairSpine_mChair_0.geometry} material={materials['m.Chair']} position={[0, 0, 0.592]} />
        </group>
        <group position={[62.801, 103.399, -11.867]} rotation={[-Math.PI / 2, 0, 0]} scale={8.852}>
          <mesh geometry={nodes.Phone_mPhone_0.geometry} material={materials['m.Phone']} />
          <mesh geometry={nodes._Tube_mPhone_0.geometry} material={materials['m.Phone']} position={[0.601, -0.14, 0.768]} scale={3.062} />
          <mesh geometry={nodes['B��zierCurve_mPhone_0'].geometry} material={materials['m.Phone']} position={[0.671, 1.268, 0.432]} scale={3.062} />
        </group>
        <group position={[32.872, 2.041, -0.099]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104}>
          <mesh geometry={nodes.Table_mTable_0.geometry} material={materials['m.Table']} />
          <mesh geometry={nodes.drawer_mTable_0.geometry} material={materials['m.Table']} position={[-3.413, 0.304, 0.743]} />
          <mesh geometry={nodes.drawer2_mTable_0.geometry} material={materials['m.Table']} position={[-3.413, 0.304, 0.743]} />
          <mesh geometry={nodes.drawer3_mTable_0.geometry} material={materials['m.Table']} position={[-3.413, 0.304, 0.743]} />
        </group>
        <mesh geometry={nodes.Cactus_mCactus_0.geometry} material={materials['m.Cactus']} position={[-73.363, 103.409, 33.332]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
        <mesh geometry={nodes.Case_mPC_0.geometry} material={materials['m.PC']} position={[0, 110.87, 13.25]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
        <mesh geometry={nodes.Computer_mPC_0.geometry} material={materials['m.PC']} position={[0, 121.034, 13.25]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
        <mesh geometry={nodes.Folder_mFolder_0.geometry} material={materials['m.Folder']} position={[42.7, 116.188, 26.246]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
        <mesh geometry={nodes.Folder001_mFolder_0.geometry} material={materials['m.Folder']} position={[60.46, 106.181, 26.246]} rotation={[-1.528, 1.55, 0]} scale={27.104} />
        <mesh geometry={nodes.Folder002_mFolder_0.geometry} material={materials['m.Folder']} position={[50.492, 121.807, 26.844]} rotation={[-1.491, -0.134, 0]} scale={27.104} />
        <mesh geometry={nodes.Folder003_mFolder_0.geometry} material={materials['m.Folder']} position={[57.49, 122.429, 24.711]} rotation={[-1.491, -0.25, -Math.PI]} scale={27.104} />
        <mesh geometry={nodes.Folder004_mFolder_0.geometry} material={materials['m.Folder']} position={[64.052, 122.059, 27.736]} rotation={[-1.491, -0.25, -3.052]} scale={27.104} />
        <mesh geometry={nodes.Keyboard_mPC_0.geometry} material={materials['m.PC']} position={[-0.148, 103.399, -31.318]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
        <mesh geometry={nodes.Mouse_mPC_0.geometry} material={materials['m.PC']} position={[-53.063, 103.395, -29.971]} rotation={[-Math.PI / 2, 0, 0]} scale={27.104} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/90s_stylized_office.glb')
