/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 retrocomputer.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RetroPC(props) {
  const { nodes, materials } = useGLTF('./models/retrocomputer.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Base_Computer_0.geometry} material={materials.Computer} />
        <mesh geometry={nodes.Mouse_Computer_0.geometry} material={materials.Computer} />
        <mesh geometry={nodes.Keyboard_Computer_0.geometry} material={materials.Computer} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/retrocomputer.glb')
