// src/sections/MoreProjects.jsx
import { useEffect, useState } from "react";

const SkeletonGrid = () => (
  <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3" aria-hidden="true">
    {Array.from({ length: 6 }).map((_, i) => (
      <div
        key={i}
        className="block p-5 rounded-xl bg-white/5 animate-pulse min-h-36"
      >
        <div className="h-5 w-2/3 rounded bg-white/10" />
        <div className="h-3 w-full rounded bg-white/10 mt-4" />
        <div className="h-3 w-5/6 rounded bg-white/10 mt-2" />
      </div>
    ))}
  </div>
);

const MoreProjects = () => {
  const [repos, setRepos] = useState([]);
  const [status, setStatus] = useState("loading");

  useEffect(() => {
    // Static snapshot generated by `npm run fetch-repos` — no runtime
    // dependency on the rate-limited GitHub API.
    const controller = new AbortController();
    fetch("./data/repos.json", { signal: controller.signal })
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => {
        setRepos(Array.isArray(data) ? data : []);
        setStatus("done");
      })
      .catch((err) => {
        if (err?.name === "AbortError") return;
        setStatus("error");
      });
    return () => controller.abort();
  }, []);

  if (status === "error") return null;

  return (
    <section id="more-projects" className="w-full mt-4 md:mt-8 px-5 md:px-20 pt-4 md:pt-8 pb-10 min-h-[40vh]">
      <h2 className="text-3xl font-semibold mb-3">More Projects</h2>
      <p className="text-white-50 text-sm mb-10">
        Dynamically fetched via the GitHub API — no manual upkeep. Refreshed
        weekly by CI, so new repos appear here automatically.
      </p>
      {status === "loading" ? (
        <SkeletonGrid />
      ) : (
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {repos.map((repo) => (
            <a
              key={repo.id}
              href={repo.html_url}
              target="_blank"
              rel="noreferrer"
              className="block p-5 rounded-xl bg-white/5 hover:bg-white/10 transition-colors"
            >
              <h3 className="text-lg font-medium">{repo.name}</h3>
              <p className="text-white-50 text-sm mt-2 line-clamp-3">
                {repo.description || "No description provided."}
              </p>
              <div className="flex gap-4 mt-4 text-xs text-white-50">
                {repo.language && <span>{repo.language}</span>}
                <span>★ {repo.stargazers_count}</span>
              </div>
            </a>
          ))}
        </div>
      )}
    </section>
  );
};

export default MoreProjects;
